{{--
    `CO-MVP-001`/`PO-CO-002` — production Privacy Policy, replacing the
    honest `public-coming-soon` stub. Drafted by Compliance Office to
    describe this application's real, verified data practices only — no
    service, processor, or capability is described that does not actually
    exist in the running application. Not a substitute for review by
    qualified legal counsel; see
    `docs/09-compliance/CO-005-LEGAL-REVIEW-REGISTER.md` for the complete
    list of items still requiring that review.
--}}
<x-public-layout title="Privacy Policy" description="What SlipGuard collects, why, and how you can control it.">

    <section class="public-hero-atmosphere bg-gradient-hero" aria-labelledby="privacy-hero-heading">
        <div class="container-marketing mx-auto px-6 py-16 sm:py-20 text-center">
            <p class="text-xs font-semibold tracking-widest text-accent-strong uppercase">{{ __('Privacy Policy') }}</p>
            <h1 id="privacy-hero-heading" class="mt-3 text-3xl sm:text-4xl font-semibold tracking-tight text-neutral-900 max-w-2xl mx-auto">
                {{ __('What SlipGuard collects, why, and how you can control it') }}
            </h1>
            <p class="mt-4 text-sm text-neutral-500">{{ __('Last updated: :date', ['date' => 'August 2026']) }}</p>
        </div>
    </section>

    <section class="public-section-quiet" aria-label="{{ __('Privacy Policy') }}" data-reveal>
        <div class="container-reading mx-auto px-4 sm:px-6 lg:px-8 py-20 space-y-10">

            <div>
                <p class="text-sm text-neutral-600">
                    {{ __('This Privacy Policy describes what SlipGuard collects when you use the Service, why, and the choices available to you. It describes what the application actually does — nothing here refers to a service, tracker, or data use that does not exist in the product.') }}
                </p>
            </div>

            <div>
                <h2 class="text-lg font-semibold text-neutral-900">{{ __('1. Information You Provide') }}</h2>
                <ul class="mt-3 space-y-3 text-sm text-neutral-600 list-disc list-outside pl-5">
                    <li><strong>{{ __('Account information:') }}</strong> {{ __('your name, email address, and password (stored as a one-way hash, never in plain text) when you register.') }}</li>
                    <li><strong>{{ __('Betting slip content:') }}</strong> {{ __('the selections you enter manually, or the screenshots/PDF documents you upload, and the text extracted from them — sport, competition, event, market, selection, and odds for each leg.') }}</li>
                    <li><strong>{{ __('Journal entries:') }}</strong> {{ __('the free-text reflections you choose to write about your own analyses.') }}</li>
                </ul>
            </div>

            <div>
                <h2 class="text-lg font-semibold text-neutral-900">{{ __('2. Information Collected Automatically') }}</h2>
                <ul class="mt-3 space-y-3 text-sm text-neutral-600 list-disc list-outside pl-5">
                    <li><strong>{{ __('Session data:') }}</strong> {{ __('a session cookie and a CSRF (cross-site request forgery protection) token, both strictly necessary to keep you securely signed in. SlipGuard does not set any analytics, advertising, or third-party tracking cookie — confirmed directly against the running application, not merely asserted.') }}</li>
                    <li><strong>{{ __('Standard server logs:') }}</strong> {{ __('IP address, browser type, and request timestamps, generated by the web server for security and troubleshooting purposes.') }}</li>
                </ul>
                <p class="mt-3 text-sm text-neutral-600">
                    {{ __('SlipGuard does not currently use any third-party analytics service (such as Google Analytics) or advertising pixel. If that ever changes, this Policy will be updated first.') }}
                </p>
            </div>

            <div>
                <h2 class="text-lg font-semibold text-neutral-900">{{ __('3. How We Use Your Information') }}</h2>
                <ul class="mt-3 space-y-3 text-sm text-neutral-600 list-disc list-outside pl-5">
                    <li>{{ __('To run the deterministic structural risk analysis you request and show you the result.') }}</li>
                    <li>{{ __('To maintain your History, Journal, and Planning History so you can revisit past analyses.') }}</li>
                    <li>{{ __('To keep your account secure (authentication, rate limiting on sign-in attempts).') }}</li>
                    <li>{{ __('To operate and improve the Service itself.') }}</li>
                </ul>
                <p class="mt-3 text-sm text-neutral-600">
                    {{ __('We do not use your betting slip content or journal entries for advertising, and we do not sell your personal data to anyone.') }}
                </p>
            </div>

            <div>
                <h2 class="text-lg font-semibold text-neutral-900">{{ __('4. Cookies') }}</h2>
                <p class="mt-2 text-sm text-neutral-600">
                    {{ __('SlipGuard uses only the session and CSRF-protection cookies described in Section 2 — both strictly necessary for the Service to function securely, and neither used for tracking or advertising. Because no non-essential cookie is set, no separate cookie-consent banner is used; this Policy is the disclosure.') }}
                </p>
            </div>

            <div>
                <h2 class="text-lg font-semibold text-neutral-900">{{ __('5. Third Parties') }}</h2>
                <p class="mt-2 text-sm text-neutral-600">
                    {{ __('We do not share your personal data with third parties for their own marketing purposes. Infrastructure providers that help us operate the Service — such as hosting and database providers — may process data strictly on our behalf, under contractual confidentiality, solely to keep the Service running. As of this Policy\'s last update, SlipGuard\'s production infrastructure has not yet been provisioned; this section will name specific providers once it has, rather than naming them speculatively now.') }}
                </p>
            </div>

            <div>
                <h2 class="text-lg font-semibold text-neutral-900">{{ __('6. Data Retention') }}</h2>
                <p class="mt-2 text-sm text-neutral-600">
                    {{ __('We retain your account and analysis data for as long as your account remains open, so your History, Journal, and Planning History stay available to you. If you delete your account (available at any time from your Profile page), your personal data is removed, other than what we are required to retain for a limited period for legitimate security or legal purposes.') }}
                </p>
            </div>

            <div>
                <h2 class="text-lg font-semibold text-neutral-900">{{ __('7. Security') }}</h2>
                <p class="mt-2 text-sm text-neutral-600">
                    {{ __('Passwords are hashed, never stored in plain text. Every customer-owned record (your slips, analyses, journal entries) is access-controlled so only you can view it — enforced at the authorization layer, independently verified, not merely declared. We encourage you to use a strong, unique password.') }}
                </p>
            </div>

            <div>
                <h2 class="text-lg font-semibold text-neutral-900">{{ __('8. Your Choices and Rights') }}</h2>
                <ul class="mt-3 space-y-3 text-sm text-neutral-600 list-disc list-outside pl-5">
                    <li>{{ __('You can review and update your account information at any time from your Profile page.') }}</li>
                    <li>{{ __('You can delete your account at any time from your Profile page.') }}</li>
                    <li>{{ __('You can delete individual slips, analyses, or journal entries you no longer want to keep, subject to the same durability rules that already apply inside the product (analysed records are archived rather than silently destroyed, to protect the integrity of your own history).') }}</li>
                </ul>
                <div class="mt-4 rounded-xl border border-amber-300 bg-amber-50 p-5" role="note">
                    <p class="text-xs font-semibold uppercase tracking-wide text-amber-800">{{ __('Requires legal review') }}</p>
                    <p class="mt-2 text-sm text-amber-900">
                        {{ __('Specific statutory data-subject rights (for example, rights under the EU/UK GDPR, such as data portability or the right to object to processing) depend on which jurisdiction(s) SlipGuard launches in — not yet named by Product Office. This section will be expanded with jurisdiction-specific rights, and a named data protection contact, once that decision and legal review are complete.') }}
                    </p>
                </div>
            </div>

            <div>
                <h2 class="text-lg font-semibold text-neutral-900">{{ __('9. Children\'s Privacy') }}</h2>
                <p class="mt-2 text-sm text-neutral-600">
                    {{ __('SlipGuard is intended for users aged 18 and over (see our Terms of Service). We do not knowingly collect information from anyone under 18.') }}
                </p>
            </div>

            <div>
                <h2 class="text-lg font-semibold text-neutral-900">{{ __('10. Changes to This Policy') }}</h2>
                <p class="mt-2 text-sm text-neutral-600">
                    {{ __('We may update this Policy as the Service evolves. We will update the "Last updated" date above whenever we do.') }}
                </p>
            </div>

            <div>
                <h2 class="text-lg font-semibold text-neutral-900">{{ __('11. Contact') }}</h2>
                <p class="mt-2 text-sm text-neutral-600">
                    {{ __('[A dedicated support and privacy contact channel has not been established yet — see the Contact page.] Questions about this Policy should be directed there once available.') }}
                </p>
            </div>

        </div>
    </section>

</x-public-layout>
